<?php
session_start();
$_SESSION['SID']=session_id();
require_once("login.php");
include("utils.php");
include("month.php");
include("logger.php");
include("family.php");
include("body.php");
print_header();
set_timezone();
print_body($link);
print_footer();
?>